import Image from "next/image";
import Link from "next/link";
import React from "react";
import s from "./page.module.css";

async function getData() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts", {
    //har gal render boganda uje refresh bogan data lani fetch qiladi
    cache: "no-store",

    // next: { revalidate: 7 },
    //har 7 sekundda fetch  qilib turadi optimization ga kotta yordam beradi
  });

  if (!res.ok) {
    throw new Error("Fail nimadur xato berdi, fetching ishlamadi!");
  }

  return res.json();
}

export const metadata = {
  title: "boburkha | Blog",
  description: "Generated by create next app",
};

const Blog = async () => {
  const data = await getData();
  return (
    <div className={s.mainContainer}>
      {data.map((item) => {
        return (
          <Link key={item.id} className={s.container} href={`/blog/${item.id}`}>
            <div className={s.imgCon}>
              <Image
                src="/csgo.jpg"
                alt="Test"
                width={400}
                height={400}
              />
            </div>
            <div className={s.content}>
              <h1>{item.title}</h1>
              <br />
              <p>{item.body}</p>
            </div>
          </Link>
        );
      })}
    </div>
  );
};

export default Blog;
